helpy:
  build: .
  restart: always
  volumes:
    - rails-assets:/helpy/public/assets
  environment:
    - POSTGRES_DB=helpy_production
    - POSTGRES_USER=helpy
    - POSTGRES_PASSWORD=some_secure_pg_password_change_in_production
    - SECRET_KEY_BASE=some_secret_key_base_change_in_production
      #- DO_NOT_PREPARE=true
  ports:
    - "80:8080"
  links:
    - postgres:postgres

postgres:
  image: postgres:9.4
  restart: always
  environment:
    - POSTGRES_DB=helpy_production
    - POSTGRES_USER=helpy
    - POSTGRES_PASSWORD=some_secure_pg_password_change_in_production
    - SECRET_KEY_BASE=some_secret_key_base_change_in_production
  volumes:
    - /home/core/dockerdata/postgres:/var/lib/postgresql/data

